import type { ReactNode } from 'react';
import { ArrowsRightLeftIcon, ChartBarIcon } from '@heroicons/react/24/outline';

export function ActiveTransfersPanel({ title, activeFiles, runningLabel, emptyLabel }: { title: string; activeFiles?: string[] | null; runningLabel: string; emptyLabel: string }) {
  const files = activeFiles ?? [];
  return <section className="ui-card space-y-4 p-5" aria-label={title}><div className="flex items-center gap-2 border-b border-[var(--color-border-light)] pb-2.5"><ArrowsRightLeftIcon className="h-4 w-4 text-[var(--color-text-muted)]" /><h3 className="font-display text-xs font-bold uppercase tracking-wider text-[var(--color-text-primary)]">{title}</h3></div>{files.length ? <div className="max-h-[465px] space-y-2 overflow-y-auto pr-1">{files.map((file, index) => <div key={`${file}-${index}`} className="flex min-w-0 items-center justify-between bg-[var(--color-bg-tertiary)] px-3.5 py-2.5 font-mono text-xs text-[var(--color-text-secondary)]"><span className="truncate pr-4" title={file}>{file.split('/').pop() || file}</span><span className="ui-badge ui-badge-success shrink-0 px-2 py-0.5 text-xs font-semibold uppercase animate-pulse">{runningLabel}</span></div>)}</div> : <p className="py-4 font-mono text-xs text-[var(--color-text-muted)]">{emptyLabel}</p>}</section>;
}

export function TransferStatusPanel({ title, rows, children }: { title: string; rows?: Array<{ label: string; value: string | number; tone?: 'default' | 'success' | 'error' }>; children?: ReactNode }) {
  const colors = { default: 'text-[var(--color-text-primary)]', success: 'text-[var(--color-success-text)]', error: 'text-[var(--color-error-text)]' };
  return <section className="ui-card space-y-4 p-5" aria-label={title}><div className="flex items-center gap-2 border-b border-[var(--color-border-light)] pb-2.5"><ChartBarIcon className="h-4 w-4 text-[var(--color-text-muted)]" /><h3 className="font-display text-xs font-bold uppercase tracking-wider text-[var(--color-text-primary)]">{title}</h3></div>{children ?? <div className="space-y-2 text-xs text-[var(--color-text-muted)]">{rows?.map((row, index) => <div key={row.label} className={`flex items-center justify-between py-1.5 ${index < rows.length - 1 ? 'border-b border-[var(--color-border-light)]' : ''}`}><span>{row.label}</span><span className={`font-mono font-bold ${colors[row.tone ?? 'default']}`}>{row.value}</span></div>)}</div>}</section>;
}
