package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func flatten(prefix string, value any, out map[string]string) {
	switch value := value.(type) {
	case map[string]any:
		for key, child := range value {
			flatten(prefix+key+".", child, out)
		}
	case string:
		out[prefix[:len(prefix)-1]] = value
	default:
		panic(fmt.Sprintf("translation value at %q must be a string or object, got %T", strings.TrimSuffix(prefix, "."), value))
	}
}

func main() {
	// go generate runs this command from the i18n package directory.
	root := filepath.Join("..", "..", "..")
	translations := map[string]map[string]string{}
	for _, language := range []string{"de", "en"} {
		raw, err := os.ReadFile(filepath.Join(root, "frontend", "src", "locales", language, "translation.json"))
		if err != nil {
			panic(err)
		}
		var document map[string]any
		if err := json.Unmarshal(raw, &document); err != nil {
			panic(err)
		}
		delivery, ok := document["delivery"]
		if !ok {
			panic("missing delivery key in " + language + " translation catalog")
		}
		out := map[string]string{}
		flatten("delivery.", delivery, out)
		translations[language] = out
	}

	keys := make([]string, 0, len(translations["de"])+len(translations["en"]))
	seen := map[string]struct{}{}
	for _, language := range []string{"de", "en"} {
		for key := range translations[language] {
			if _, ok := seen[key]; !ok {
				seen[key] = struct{}{}
				keys = append(keys, key)
			}
		}
	}
	sort.Strings(keys)
	for _, language := range []string{"de", "en"} {
		for _, key := range keys {
			if _, ok := translations[language][key]; !ok {
				panic(fmt.Sprintf("delivery locale key mismatch: %s is missing %q", language, key))
			}
		}
	}

	var generated bytes.Buffer
	fmt.Fprintln(&generated, "// Code generated by go generate; DO NOT EDIT.\npackage i18n\n\nvar translations = map[string]map[string]string{")
	for _, language := range []string{"de", "en"} {
		fmt.Fprintf(&generated, "%q: {\n", language)
		for _, key := range keys {
			fmt.Fprintf(&generated, "%q: %s,\n", key, strconv.Quote(translations[language][key]))
		}
		fmt.Fprintln(&generated, "},")
	}
	fmt.Fprintln(&generated, "}")

	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("translations_gen.go", formatted, 0o644); err != nil {
		panic(err)
	}
}
