package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
)

func flatten(prefix string, value any, out map[string]string) {
	switch value := value.(type) {
	case map[string]any:
		for key, child := range value {
			flatten(prefix+key+".", child, out)
		}
	case string:
		out[prefix[:len(prefix)-1]] = value
	}
}

func main() {
	root := filepath.Join("..", "..", "..")
	translations := map[string]map[string]string{}
	for _, language := range []string{"de", "en"} {
		raw, err := os.ReadFile(filepath.Join(root, "frontend", "src", "locales", language, "translation.json"))
		if err != nil {
			panic(err)
		}
		var document map[string]any
		if err := json.Unmarshal(raw, &document); err != nil {
			panic(err)
		}
		out := map[string]string{}
		flatten("delivery.", document["delivery"], out)
		translations[language] = out
	}
	keys := make([]string, 0, len(translations["en"]))
	for key := range translations["en"] {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	f, err := os.Create("translations_gen.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()
	fmt.Fprintln(f, "// Code generated by go generate; DO NOT EDIT.\npackage i18n\n\nvar translations = map[string]map[string]string{")
	for _, language := range []string{"de", "en"} {
		fmt.Fprintf(f, "%q: {\n", language)
		for _, key := range keys {
			fmt.Fprintf(f, "%q: %s,\n", key, strconv.Quote(translations[language][key]))
		}
		fmt.Fprintln(f, "},")
	}
	fmt.Fprintln(f, "}")
}
